spring:
  datasource:
    username: root
    password: Wjq18896059378
    url: jdbc:mysql://localhost:3306/produce?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
